In [58]:
import pandas as pd
df_cons = pd.read_csv("eco2mix-regional-cons-def.csv", sep=';',low_memory=False )

In [59]:
colonnes_a_supprimer = ['Column 30','Stockage batterie', 'Déstockage batterie','Nature' ]
df_cons.drop(columns=colonnes_a_supprimer, inplace=True)
#df_cons['Echange Import (MW)'] = df_cons['Ech. physiques (MW)'].apply(lambda x: x if x > 0 else 0)
#df_cons['Echange Export (MW)'] = df_cons['Ech. physiques (MW)'].apply(lambda x: abs(x) if x < 0 else 0)
df_cons['Eolien (MW)'] = pd.to_numeric(df_cons['Eolien (MW)'], errors='coerce')

In [60]:
# Tri par région (colonne 'Région')
df_sorted = df_cons.sort_values(by='Date - Heure')

# Réinitialiser les index après tri
df_sorted = df_sorted.reset_index(drop=True)

df_cleaned = df_sorted[df_sorted['Heure'].str.endswith(':00')]
df_cleaned['Consommation_MWh'] = df_cleaned['Consommation (MW)'] * 0.5
# Supprimer une ligne sur deux (conserver les lignes d'indice pair)
#df_cleaned = df_sorted.iloc[::2]
df_cleaned

/var/folders/95/c07zk0g150xgjccxhtynkw8w0000gn/T/ipykernel_15694/443257290.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['Consommation_MWh'] = df_cleaned['Consommation (MW)'] * 0.5

,Code INSEE région,Région,Date,Heure,Date - Heure,Consommation (MW),Thermique (MW),Nucléaire (MW),Eolien (MW),Solaire (MW),...,TCH Nucléaire (%),TCO Eolien (%),TCH Eolien (%),TCO Solaire (%),TCH Solaire (%),TCO Hydraulique (%),TCH Hydraulique (%),TCO Bioénergies (%),TCH Bioénergies (%),Consommation_MWh
0,76,Occitanie,2013-01-01,00:00,2012-12-31T23:00:00+00:00,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,24,Centre-Val de Loire,2013-01-01,00:00,2012-12-31T23:00:00+00:00,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,52,Pays de la Loire,2013-01-01,00:00,2012-12-31T23:00:00+00:00,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,75,Nouvelle-Aquitaine,2013-01-01,00:00,2012-12-31T23:00:00+00:00,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,53,Bretagne,2013-01-01,00:00,2012-12-31T23:00:00+00:00,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2121391,11,Île-de-France,2023-01-31,23:00,2023-01-31T22:00:00+00:00,9718.0,381.0,0.0,58.0,0.0,...,NaN,0.60,40.00,0.0,0.0,0.08,42.11,1.57,47.96,4859.0
2121392,53,Bretagne,2023-01-31,23:00,2023-01-31T22:00:00+00:00,3148.0,684.0,0.0,113.0,0.0,...,NaN,3.59,8.66,0.0,0.0,1.30,14.91,1.75,75.34,1574.0
2121393,84,Auvergne-Rhône-Alpes,2023-01-31,23:00,2023-01-31T22:00:00+00:00,9839.0,402.0,13327.0,156.0,0.0,...,98.21,1.59,21.58,0.0,0.0,38.49,33.21,1.12,57.59,4919.5
2121394,75,Nouvelle-Aquitaine,2023-01-31,23:00,2023-01-31T22:00:00+00:00,5936.0,157.0,3669.0,40.0,0.0,...,55.34,0.67,2.53,0.0,0.0,6.28,16.64,1.87,34.05,2968.0
2121395,93,Provence-Alpes-Côte d'Azur,2023-01-31,23:00,2023-01-31T22:00:00+00:00,6176.0,314.0,0.0,42.0,0.0,...,NaN,0.68,43.75,0.0,0.0,30.47,57.66,1.38,28.62,3088.0

In [ ]:
# Exporter en CSV
df_cleaned.to_csv("eco2mix-regional_reduced.csv", sep=',', index=False)
df_cleaned

,Code INSEE région,Région,Date,Heure,Date - Heure,Consommation (MW),Thermique (MW),Nucléaire (MW),Eolien (MW),Solaire (MW),...,TCH Nucléaire (%),TCO Eolien (%),TCH Eolien (%),TCO Solaire (%),TCH Solaire (%),TCO Hydraulique (%),TCH Hydraulique (%),TCO Bioénergies (%),TCH Bioénergies (%),Consommation_MWh
0,76,Occitanie,2013-01-01,00:00,2012-12-31T23:00:00+00:00,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,24,Centre-Val de Loire,2013-01-01,00:00,2012-12-31T23:00:00+00:00,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,52,Pays de la Loire,2013-01-01,00:00,2012-12-31T23:00:00+00:00,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,75,Nouvelle-Aquitaine,2013-01-01,00:00,2012-12-31T23:00:00+00:00,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,53,Bretagne,2013-01-01,00:00,2012-12-31T23:00:00+00:00,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2121391,11,Île-de-France,2023-01-31,23:00,2023-01-31T22:00:00+00:00,9718.0,381.0,0.0,58.0,0.0,...,NaN,0.60,40.00,0.0,0.0,0.08,42.11,1.57,47.96,4859.0
2121392,53,Bretagne,2023-01-31,23:00,2023-01-31T22:00:00+00:00,3148.0,684.0,0.0,113.0,0.0,...,NaN,3.59,8.66,0.0,0.0,1.30,14.91,1.75,75.34,1574.0
2121393,84,Auvergne-Rhône-Alpes,2023-01-31,23:00,2023-01-31T22:00:00+00:00,9839.0,402.0,13327.0,156.0,0.0,...,98.21,1.59,21.58,0.0,0.0,38.49,33.21,1.12,57.59,4919.5
2121394,75,Nouvelle-Aquitaine,2023-01-31,23:00,2023-01-31T22:00:00+00:00,5936.0,157.0,3669.0,40.0,0.0,...,55.34,0.67,2.53,0.0,0.0,6.28,16.64,1.87,34.05,2968.0
2121395,93,Provence-Alpes-Côte d'Azur,2023-01-31,23:00,2023-01-31T22:00:00+00:00,6176.0,314.0,0.0,42.0,0.0,...,NaN,0.68,43.75,0.0,0.0,30.47,57.66,1.38,28.62,3088.0

In [62]:
df= pd.read_csv("eco2mix-regional_reduced.csv", sep=',',low_memory=False )
df

,Code INSEE région,Région,Date,Heure,Date - Heure,Consommation (MW),Thermique (MW),Nucléaire (MW),Eolien (MW),Solaire (MW),...,TCH Nucléaire (%),TCO Eolien (%),TCH Eolien (%),TCO Solaire (%),TCH Solaire (%),TCO Hydraulique (%),TCH Hydraulique (%),TCO Bioénergies (%),TCH Bioénergies (%),Consommation_MWh
0,76,Occitanie,2013-01-01,00:00,2012-12-31T23:00:00+00:00,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,24,Centre-Val de Loire,2013-01-01,00:00,2012-12-31T23:00:00+00:00,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,52,Pays de la Loire,2013-01-01,00:00,2012-12-31T23:00:00+00:00,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,75,Nouvelle-Aquitaine,2013-01-01,00:00,2012-12-31T23:00:00+00:00,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,53,Bretagne,2013-01-01,00:00,2012-12-31T23:00:00+00:00,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1060699,11,Île-de-France,2023-01-31,23:00,2023-01-31T22:00:00+00:00,9718.0,381.0,0.0,58.0,0.0,...,NaN,0.60,40.00,0.0,0.0,0.08,42.11,1.57,47.96,4859.0
1060700,53,Bretagne,2023-01-31,23:00,2023-01-31T22:00:00+00:00,3148.0,684.0,0.0,113.0,0.0,...,NaN,3.59,8.66,0.0,0.0,1.30,14.91,1.75,75.34,1574.0
1060701,84,Auvergne-Rhône-Alpes,2023-01-31,23:00,2023-01-31T22:00:00+00:00,9839.0,402.0,13327.0,156.0,0.0,...,98.21,1.59,21.58,0.0,0.0,38.49,33.21,1.12,57.59,4919.5
1060702,75,Nouvelle-Aquitaine,2023-01-31,23:00,2023-01-31T22:00:00+00:00,5936.0,157.0,3669.0,40.0,0.0,...,55.34,0.67,2.53,0.0,0.0,6.28,16.64,1.87,34.05,2968.0
1060703,93,Provence-Alpes-Côte d'Azur,2023-01-31,23:00,2023-01-31T22:00:00+00:00,6176.0,314.0,0.0,42.0,0.0,...,NaN,0.68,43.75,0.0,0.0,30.47,57.66,1.38,28.62,3088.0

In [63]:
df['DH'] = pd.to_datetime(df_cons['Date - Heure'], errors='coerce')
df

,Code INSEE région,Région,Date,Heure,Date - Heure,Consommation (MW),Thermique (MW),Nucléaire (MW),Eolien (MW),Solaire (MW),...,TCO Eolien (%),TCH Eolien (%),TCO Solaire (%),TCH Solaire (%),TCO Hydraulique (%),TCH Hydraulique (%),TCO Bioénergies (%),TCH Bioénergies (%),Consommation_MWh,DH
0,76,Occitanie,2013-01-01,00:00,2012-12-31T23:00:00+00:00,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2012-12-31 23:00:00+00:00
1,24,Centre-Val de Loire,2013-01-01,00:00,2012-12-31T23:00:00+00:00,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2012-12-31 23:00:00+00:00
2,52,Pays de la Loire,2013-01-01,00:00,2012-12-31T23:00:00+00:00,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2012-12-31 23:00:00+00:00
3,75,Nouvelle-Aquitaine,2013-01-01,00:00,2012-12-31T23:00:00+00:00,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2012-12-31 23:00:00+00:00
4,53,Bretagne,2013-01-01,00:00,2012-12-31T23:00:00+00:00,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2012-12-31 23:00:00+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1060699,11,Île-de-France,2023-01-31,23:00,2023-01-31T22:00:00+00:00,9718.0,381.0,0.0,58.0,0.0,...,0.60,40.00,0.0,0.0,0.08,42.11,1.57,47.96,4859.0,2018-01-16 10:30:00+00:00
1060700,53,Bretagne,2023-01-31,23:00,2023-01-31T22:00:00+00:00,3148.0,684.0,0.0,113.0,0.0,...,3.59,8.66,0.0,0.0,1.30,14.91,1.75,75.34,1574.0,2018-01-16 10:30:00+00:00
1060701,84,Auvergne-Rhône-Alpes,2023-01-31,23:00,2023-01-31T22:00:00+00:00,9839.0,402.0,13327.0,156.0,0.0,...,1.59,21.58,0.0,0.0,38.49,33.21,1.12,57.59,4919.5,2018-01-16 10:30:00+00:00
1060702,75,Nouvelle-Aquitaine,2023-01-31,23:00,2023-01-31T22:00:00+00:00,5936.0,157.0,3669.0,40.0,0.0,...,0.67,2.53,0.0,0.0,6.28,16.64,1.87,34.05,2968.0,2018-01-16 10:30:00+00:00
1060703,93,Provence-Alpes-Côte d'Azur,2023-01-31,23:00,2023-01-31T22:00:00+00:00,6176.0,314.0,0.0,42.0,0.0,...,0.68,43.75,0.0,0.0,30.47,57.66,1.38,28.62,3088.0,2018-01-16 10:30:00+00:00